pub mod mysql;
pub mod postgres;
pub mod sqlite;

/// IR v2: opt-in emit entrypoints (WIP, not all constraints mapped yet)
pub mod v2 {
	use xsql_ir::v2::*;

	   pub fn emit_mysql_v2(schema: &V2Schema) -> String {
		   let mut out = String::new();
		   for table in &schema.tables {
			   out.push_str(&format!("CREATE TABLE {} (\n", table.name));
			   let mut defs = Vec::new();
			   for col in &table.columns {
				   let ty = match &col.data_type {
					   V2DataType::Integer { bits: Some(64) } => "BIGINT".to_string(),
					   V2DataType::Integer { bits: Some(16) } => "SMALLINT".to_string(),
					   V2DataType::Integer { bits: _ } => "INT".to_string(),
					   V2DataType::Boolean => "TINYINT(1)".to_string(),
					   V2DataType::Float => "FLOAT".to_string(),
					   V2DataType::Double => "DOUBLE".to_string(),
					   V2DataType::Varchar(Some(n)) => format!("VARCHAR({})", n),
					   V2DataType::Varchar(None) => "VARCHAR(255)".to_string(),
					   V2DataType::Text => "TEXT".to_string(),
					   V2DataType::Timestamp => "DATETIME".to_string(),
					   V2DataType::Custom(s) => s.clone(),
				   };
				   let mut line = format!("  {} {}", col.name, ty);
				   for c in &col.constraints {
					   match c {
						   ColumnConstraint::NotNull => line.push_str(" NOT NULL"),
						   ColumnConstraint::Default(expr) => line.push_str(&format!(" DEFAULT {}", expr)),
						   ColumnConstraint::AutoIncrement => line.push_str(" AUTO_INCREMENT"),
						   ColumnConstraint::Check(expr) => line.push_str(&format!(" CHECK ({})", expr)),
					   }
				   }
				   defs.push(line);
			   }
			   if let Some(pk) = &table.primary_key {
				   defs.push(format!("  PRIMARY KEY ({})", pk.join(", ")));
			   }
			   for c in &table.constraints {
				   match c {
					   Constraint::Unique { name, columns } => {
						   let n = name.as_ref().map(|n| format!(" CONSTRAINT {}", n)).unwrap_or_default();
						   defs.push(format!("  {}UNIQUE ({})", n, columns.join(", ")));
					   }
					   Constraint::ForeignKey(fk) => {
						   let n = fk.name.as_ref().map(|n| format!(" CONSTRAINT {}", n)).unwrap_or_default();
						   let mut line = format!("  {}FOREIGN KEY ({}) REFERENCES {}({})", n, fk.columns.join(", "), fk.referenced_table, fk.referenced_columns.join(", "));
						   if let Some(on_update) = &fk.on_update {
							   line.push_str(&format!(" ON UPDATE {}", on_update));
						   }
						   if let Some(on_delete) = &fk.on_delete {
							   line.push_str(&format!(" ON DELETE {}", on_delete));
						   }
						   defs.push(line);
					   }
					   Constraint::Check { name, expr } => {
						   let n = name.as_ref().map(|n| format!(" CONSTRAINT {}", n)).unwrap_or_default();
						   defs.push(format!("  {}CHECK ({})", n, expr));
					   }
				   }
			   }
			   out.push_str(&defs.join(",\n"));
			   out.push_str("\n);\n\n");
		   }
		   out
	   }
	   pub fn emit_postgres_v2(schema: &V2Schema) -> String {
		   let mut out = String::new();
		   for table in &schema.tables {
			   out.push_str(&format!("CREATE TABLE {} (\n", table.name));
			   let mut defs = Vec::new();
			   for col in &table.columns {
				   let ty = match &col.data_type {
					   V2DataType::Integer { bits: Some(64) } => "BIGINT".to_string(),
					   V2DataType::Integer { bits: Some(16) } => "SMALLINT".to_string(),
					   V2DataType::Integer { bits: _ } => "INTEGER".to_string(),
					   V2DataType::Boolean => "BOOLEAN".to_string(),
					   V2DataType::Float => "REAL".to_string(),
					   V2DataType::Double => "DOUBLE PRECISION".to_string(),
					   V2DataType::Varchar(Some(n)) => format!("VARCHAR({})", n),
					   V2DataType::Varchar(None) => "VARCHAR".to_string(),
					   V2DataType::Text => "TEXT".to_string(),
					   V2DataType::Timestamp => "TIMESTAMP".to_string(),
					   V2DataType::Custom(s) => s.clone(),
				   };
				   let mut line = format!("  {} {}", col.name, ty);
				   for c in &col.constraints {
					   match c {
						   ColumnConstraint::NotNull => line.push_str(" NOT NULL"),
						   ColumnConstraint::Default(expr) => line.push_str(&format!(" DEFAULT {}", expr)),
						   ColumnConstraint::AutoIncrement => line.push_str(" GENERATED BY DEFAULT AS IDENTITY"),
						   ColumnConstraint::Check(expr) => line.push_str(&format!(" CHECK ({})", expr)),
					   }
				   }
				   defs.push(line);
			   }
			   // Table-level constraints
			   if let Some(pk) = &table.primary_key {
				   defs.push(format!("  PRIMARY KEY ({})", pk.join(", ")));
			   }
			   for c in &table.constraints {
				   match c {
					   Constraint::Unique { name, columns } => {
						   let n = name.as_ref().map(|n| format!(" CONSTRAINT {}", n)).unwrap_or_default();
						   defs.push(format!("  {}UNIQUE ({})", n, columns.join(", ")));
					   }
					   Constraint::ForeignKey(fk) => {
						   let n = fk.name.as_ref().map(|n| format!(" CONSTRAINT {}", n)).unwrap_or_default();
						   let mut line = format!("  {}FOREIGN KEY ({}) REFERENCES {}({})", n, fk.columns.join(", "), fk.referenced_table, fk.referenced_columns.join(", "));
						   if let Some(on_update) = &fk.on_update {
							   line.push_str(&format!(" ON UPDATE {}", on_update));
						   }
						   if let Some(on_delete) = &fk.on_delete {
							   line.push_str(&format!(" ON DELETE {}", on_delete));
						   }
						   defs.push(line);
					   }
					   Constraint::Check { name, expr } => {
						   let n = name.as_ref().map(|n| format!(" CONSTRAINT {}", n)).unwrap_or_default();
						   defs.push(format!("  {}CHECK ({})", n, expr));
					   }
				   }
			   }
			   out.push_str(&defs.join(",\n"));
			   out.push_str("\n);\n\n");
		   }
		   out
	   }
	   pub fn emit_sqlite_v2(schema: &V2Schema) -> String {
		   let mut out = String::new();
		   for table in &schema.tables {
			   out.push_str(&format!("CREATE TABLE {} (\n", table.name));
			   let mut defs = Vec::new();
			   for col in &table.columns {
				   let ty = match &col.data_type {
					   V2DataType::Integer { .. } => "INTEGER".to_string(),
					   V2DataType::Boolean => "INTEGER".to_string(),
					   V2DataType::Float | V2DataType::Double => "REAL".to_string(),
					   V2DataType::Varchar(_) | V2DataType::Text | V2DataType::Custom(_) => "TEXT".to_string(),
					   V2DataType::Timestamp => "TEXT".to_string(),
				   };
				   let mut line = format!("  {} {}", col.name, ty);
				   for c in &col.constraints {
					   match c {
						   ColumnConstraint::NotNull => line.push_str(" NOT NULL"),
						   ColumnConstraint::Default(expr) => line.push_str(&format!(" DEFAULT {}", expr)),
						   ColumnConstraint::AutoIncrement => line.push_str(" PRIMARY KEY AUTOINCREMENT"),
						   ColumnConstraint::Check(expr) => line.push_str(&format!(" CHECK ({})", expr)),
					   }
				   }
				   defs.push(line);
			   }
			   if let Some(pk) = &table.primary_key {
				   defs.push(format!("  PRIMARY KEY ({})", pk.join(", ")));
			   }
			   for c in &table.constraints {
				   match c {
					   Constraint::Unique { name, columns } => {
						   let n = name.as_ref().map(|n| format!(" CONSTRAINT {}", n)).unwrap_or_default();
						   defs.push(format!("  {}UNIQUE ({})", n, columns.join(", ")));
					   }
					   Constraint::ForeignKey(fk) => {
						   let n = fk.name.as_ref().map(|n| format!(" CONSTRAINT {}", n)).unwrap_or_default();
						   let mut line = format!("  {}FOREIGN KEY ({}) REFERENCES {}({})", n, fk.columns.join(", "), fk.referenced_table, fk.referenced_columns.join(", "));
						   if let Some(on_update) = &fk.on_update {
							   line.push_str(&format!(" ON UPDATE {}", on_update));
						   }
						   if let Some(on_delete) = &fk.on_delete {
							   line.push_str(&format!(" ON DELETE {}", on_delete));
						   }
						   defs.push(line);
					   }
					   Constraint::Check { name, expr } => {
						   let n = name.as_ref().map(|n| format!(" CONSTRAINT {}", n)).unwrap_or_default();
						   defs.push(format!("  {}CHECK ({})", n, expr));
					   }
				   }
			   }
			   out.push_str(&defs.join(",\n"));
			   out.push_str("\n);\n\n");
		   }
		   out
	   }
}
