use xsql_ir::*;

pub fn emit_postgres(schema: &Schema) -> String {
    let mut out = String::new();

    for table in &schema.tables {
        out.push_str(&format!("CREATE TABLE {} (\n", table.name));

        for (i, col) in table.columns.iter().enumerate() {
            let ty = match col.data_type {
                DataType::Int => "INTEGER".to_string(),
                DataType::BigInt => "BIGINT".to_string(),
                DataType::Boolean => "BOOLEAN".to_string(),
                DataType::Float => "REAL".to_string(),
                DataType::Double => "DOUBLE PRECISION".to_string(),
                DataType::Varchar(Some(n)) => format!("VARCHAR({})", n),
                DataType::Varchar(None) => "VARCHAR".to_string(),
                DataType::Text => "TEXT".to_string(),
                DataType::Timestamp => "TIMESTAMP".to_string(),
            };

            out.push_str(&format!("  {} {}", col.name, ty));

            if col.auto_increment {
                out.push_str(" GENERATED BY DEFAULT AS IDENTITY");
            }

            if !col.nullable {
                out.push_str(" NOT NULL");
            }

            if i < table.columns.len() - 1 || table.primary_key.is_some() {
                out.push(',');
            }
            out.push('\n');
        }

        if let Some(pk) = &table.primary_key {
            out.push_str(&format!("  PRIMARY KEY ({})\n", pk.join(", ")));
        }

        out.push_str(");\n\n");
    }

    out
}
